import type { VideoSpec } from './types';
import { ASSET_REGISTRY } from '@/lib/assets/registry';

export const SAMPLE_SHOWCASE_SPEC: VideoSpec = {
  version: '2.0.0',
  id: 'showcase-ai-infrastructure-2026',
  title: "The Race to Build the World's Most Powerful AI Infrastructure",
  description: 'A 45-second premium documentary investigation into the global semiconductor and hyperscale compute race.',
  composition: {
    format: '9:16',
    width: 1080,
    height: 1920,
    fps: 30,
    durationInFrames: 1350, // 45s @ 30fps
  },
  brand: {
    brandId: 'catalyst-editorial',
    name: 'Catalyst Editorial',
    colors: {
      primary: '#f0522a',
      secondary: '#00c9a7',
      accent: '#ffd166',
      background: '#0b0d13',
      surface: '#161922',
      text: '#f8fafc',
      textMuted: '#94a3b8',
    },
    typography: {
      fontFamilyHeading: 'Inter, system-ui, sans-serif',
      fontFamilyBody: 'Inter, system-ui, sans-serif',
      fontFamilyMono: 'JetBrains Mono, monospace',
      headingWeight: '900',
      bodyWeight: '500',
    },
    motionStyle: 'editorial',
    textures: {
      paperTexture: true,
      grainIntensity: 0.08,
      halftoneEffect: false,
      vignette: true,
    },
    captionStyle: {
      preset: 'vox-editorial',
      fontSize: 44,
      highlightColor: '#ffd166',
      activeTextColor: '#0b0d13',
      inactiveTextColor: '#ffffff',
      boxBackground: 'rgba(11, 13, 19, 0.88)',
    },
  },
  narration: {
    durationSeconds: 45,
    transcript: 'The global AI chip race is accelerating at an unprecedented pace. Behind every foundation model lies a multi-billion dollar semiconductor fabrication supply chain. In just twenty-four months, compute density per megawatt surged by more than four hundred percent. Across Taiwan, Silicon Valley, and Europe, sovereign clusters are linking high-bandwidth optical grids. By compiling algorithms directly into physical silicon logic, software latency is completely eliminated. The result is a hundred-fold expansion in total throughput, transforming global digital intelligence. This is not just faster computing. It is the physical foundation of the next era.',
    words: [
      // Scene 1: 0.0 - 5.0s (150 frames)
      { word: 'The', start: 0.2, end: 0.4 },
      { word: 'global', start: 0.45, end: 0.9 },
      { word: 'AI', start: 0.95, end: 1.25 },
      { word: 'chip', start: 1.3, end: 1.65 },
      { word: 'race', start: 1.7, end: 2.15 },
      { word: 'is', start: 2.2, end: 2.4 },
      { word: 'accelerating', start: 2.45, end: 3.3 },
      { word: 'at', start: 3.35, end: 3.55 },
      { word: 'an', start: 3.6, end: 3.75 },
      { word: 'unprecedented', start: 3.8, end: 4.5 },
      { word: 'pace.', start: 4.55, end: 4.95 },

      // Scene 2: 5.0 - 11.0s (180 frames)
      { word: 'Behind', start: 5.1, end: 5.55 },
      { word: 'every', start: 5.6, end: 5.95 },
      { word: 'foundation', start: 6.0, end: 6.6 },
      { word: 'model', start: 6.65, end: 7.1 },
      { word: 'lies', start: 7.15, end: 7.45 },
      { word: 'a', start: 7.5, end: 7.65 },
      { word: 'multi-billion', start: 7.7, end: 8.4 },
      { word: 'dollar', start: 8.45, end: 8.85 },
      { word: 'semiconductor', start: 8.9, end: 9.65 },
      { word: 'fabrication', start: 9.7, end: 10.35 },
      { word: 'supply', start: 10.4, end: 10.7 },
      { word: 'chain.', start: 10.75, end: 10.95 },

      // Scene 3: 11.0 - 18.0s (210 frames)
      { word: 'In', start: 11.1, end: 11.3 },
      { word: 'just', start: 11.35, end: 11.65 },
      { word: 'twenty-four', start: 11.7, end: 12.35 },
      { word: 'months,', start: 12.4, end: 12.9 },
      { word: 'compute', start: 13.0, end: 13.5 },
      { word: 'density', start: 13.55, end: 14.05 },
      { word: 'per', start: 14.1, end: 14.35 },
      { word: 'megawatt', start: 14.4, end: 15.0 },
      { word: 'surged', start: 15.1, end: 15.65 },
      { word: 'by', start: 15.7, end: 15.9 },
      { word: 'more', start: 15.95, end: 16.25 },
      { word: 'than', start: 16.3, end: 16.5 },
      { word: 'four', start: 16.55, end: 16.85 },
      { word: 'hundred', start: 16.9, end: 17.35 },
      { word: 'percent.', start: 17.4, end: 17.9 },

      // Scene 4: 18.0 - 25.0s (210 frames)
      { word: 'Across', start: 18.1, end: 18.55 },
      { word: 'Taiwan,', start: 18.6, end: 19.2 },
      { word: 'Silicon', start: 19.3, end: 19.75 },
      { word: 'Valley,', start: 19.8, end: 20.35 },
      { word: 'and', start: 20.4, end: 20.6 },
      { word: 'Europe,', start: 20.65, end: 21.2 },
      { word: 'sovereign', start: 21.3, end: 21.85 },
      { word: 'clusters', start: 21.9, end: 22.45 },
      { word: 'are', start: 22.5, end: 22.7 },
      { word: 'linking', start: 22.75, end: 23.2 },
      { word: 'high-bandwidth', start: 23.25, end: 24.1 },
      { word: 'optical', start: 24.15, end: 24.55 },
      { word: 'grids.', start: 24.6, end: 24.95 },

      // Scene 5: 25.0 - 33.0s (240 frames)
      { word: 'By', start: 25.1, end: 25.3 },
      { word: 'compiling', start: 25.35, end: 26.0 },
      { word: 'algorithms', start: 26.05, end: 26.8 },
      { word: 'directly', start: 26.85, end: 27.45 },
      { word: 'into', start: 27.5, end: 27.8 },
      { word: 'physical', start: 27.85, end: 28.45 },
      { word: 'silicon', start: 28.5, end: 29.05 },
      { word: 'logic,', start: 29.1, end: 29.65 },
      { word: 'software', start: 29.8, end: 30.35 },
      { word: 'latency', start: 30.4, end: 30.95 },
      { word: 'is', start: 31.0, end: 31.2 },
      { word: 'completely', start: 31.25, end: 32.1 },
      { word: 'eliminated.', start: 32.15, end: 32.95 },

      // Scene 6: 33.0 - 40.0s (210 frames)
      { word: 'The', start: 33.1, end: 33.3 },
      { word: 'result', start: 33.35, end: 33.75 },
      { word: 'is', start: 33.8, end: 34.0 },
      { word: 'a', start: 34.05, end: 34.2 },
      { word: 'hundred-fold', start: 34.25, end: 35.15 },
      { word: 'expansion', start: 35.2, end: 35.85 },
      { word: 'in', start: 35.9, end: 36.1 },
      { word: 'total', start: 36.15, end: 36.55 },
      { word: 'throughput,', start: 36.6, end: 37.35 },
      { word: 'transforming', start: 37.45, end: 38.25 },
      { word: 'global', start: 38.3, end: 38.75 },
      { word: 'digital', start: 38.8, end: 39.25 },
      { word: 'intelligence.', start: 39.3, end: 39.95 },

      // Scene 7: 40.0 - 45.0s (150 frames)
      { word: 'This', start: 40.1, end: 40.4 },
      { word: 'is', start: 40.45, end: 40.65 },
      { word: 'not', start: 40.7, end: 40.95 },
      { word: 'just', start: 41.0, end: 41.25 },
      { word: 'faster', start: 41.3, end: 41.75 },
      { word: 'computing.', start: 41.8, end: 42.6 },
      { word: 'It', start: 42.75, end: 42.95 },
      { word: 'is', start: 43.0, end: 43.2 },
      { word: 'the', start: 43.25, end: 43.45 },
      { word: 'physical', start: 43.5, end: 44.0 },
      { word: 'foundation', start: 44.05, end: 44.6 },
      { word: 'of', start: 44.65, end: 44.8 },
      { word: 'the', start: 44.85, end: 45.0 },
    ],
  },
  scenes: [
    // Scene 1 (0–5s = 150 frames): HERO HOOK
    {
      id: 'scene-1',
      sceneNumber: 1,
      type: 'hook',
      templateId: 'hook-primary',
      title: 'The AI Infrastructure Race',
      startFrame: 0,
      durationFrames: 150,
      narrationText: 'The global AI chip race is accelerating at an unprecedented pace.',
      visualIntent: 'Establish massive technological scale with full-frame supercomputer photography',
      visualType: 'cinematic-photo',
      primarySubject: 'Massive AI Supercomputing Cluster',
      visualMetaphor: 'Illuminated optical nerve center of modern artificial intelligence',
      camera: { type: 'push', intensity: 0.22, startScale: 1.0, endScale: 1.14 },
      composition: { layout: 'full-frame', subjectPosition: 'center', scale: 1.05 },
      typography: {
        headline: 'THE GLOBAL AI CHIP RACE',
        supportingText: 'The trillion-dollar battle for sovereign compute power',
        hierarchy: 'DISPLAY',
        position: 'center',
        emphasisWords: ['GLOBAL', 'AI', 'CHIP', 'RACE'],
      },
      visualLanguage: 'cinematic-photo',
      visualBeats: [
        {
          id: 's1-b1',
          beatIndex: 0,
          startFrame: 0,
          durationInFrames: 75,
          narrativePurpose: 'Establish massive technological scale',
          visualIntent: 'Full-frame datacenter cluster with optical fiber glow',
          primaryVisual: 'cinematic-photo',
          secondaryVisuals: [],
          assets: [{
            type: 'photo',
            subject: 'Hyperscale GPU Datacenter Cluster',
            url: ASSET_REGISTRY[0].url,
            treatment: 'cinematic_macro',
            aspectRatio: '16:9',
          }],
          layers: ['background', 'subject', 'typography'],
          camera: { movement: 'push', intensity: 0.22, easing: 'ease-out', focalPoint: { x: 50, y: 50 } },
          motion: ['spring_in'],
          typography: {
            treatment: 'editorial_kinetic',
            headline: 'THE GLOBAL AI CHIP RACE',
            emphasisWords: ['GLOBAL', 'AI', 'CHIP', 'RACE'],
            position: 'center',
          },
          transition: { type: 'fade', durationFrames: 10, sharedGeometry: 'none', direction: 'right' },
          props: {
            imageUrl: ASSET_REGISTRY[0].url,
            headline: 'THE GLOBAL AI CHIP RACE',
            subtext: 'The trillion-dollar battle for sovereign compute power',
            tag: 'DOCUMENTARY INVESTIGATION',
          },
        },
        {
          id: 's1-b2',
          beatIndex: 1,
          startFrame: 75,
          durationInFrames: 75,
          narrativePurpose: 'Deepen visual immersion with camera push',
          visualIntent: 'Intensify focus on glowing optical interconnects',
          primaryVisual: 'cinematic-photo',
          secondaryVisuals: [],
          assets: [{
            type: 'photo',
            subject: 'Hyperscale GPU Datacenter Cluster',
            url: ASSET_REGISTRY[0].url,
            treatment: 'cinematic_macro',
            aspectRatio: '16:9',
          }],
          layers: ['background', 'subject', 'typography'],
          camera: { movement: 'push', intensity: 0.28, easing: 'ease-out', focalPoint: { x: 50, y: 50 } },
          motion: ['slow_drift'],
          typography: {
            treatment: 'keyword_spotlight',
            headline: 'UNPRECEDENTED VELOCITY',
            emphasisWords: ['UNPRECEDENTED'],
            position: 'center',
          },
          transition: { type: 'fade', durationFrames: 10, sharedGeometry: 'none', direction: 'right' },
          props: {
            imageUrl: ASSET_REGISTRY[0].url,
            headline: 'THE GLOBAL AI CHIP RACE',
            subtext: 'The trillion-dollar battle for sovereign compute power',
            tag: 'DOCUMENTARY INVESTIGATION',
          },
        },
      ],
      props: {
        imageUrl: ASSET_REGISTRY[0].url,
        headline: 'THE GLOBAL AI CHIP RACE',
        subtext: 'The trillion-dollar battle for sovereign compute power',
        tag: 'DOCUMENTARY INVESTIGATION',
        highlightWords: ['GLOBAL', 'AI', 'CHIP', 'RACE'],
      },
    },

    // Scene 2 (5–11s = 180 frames): GLOBAL CONTEXT
    {
      id: 'scene-2',
      sceneNumber: 2,
      type: 'editorial',
      templateId: 'editorial-quote',
      title: 'The Fabrication Supply Chain',
      startFrame: 150,
      durationFrames: 180,
      narrationText: 'Behind every foundation model lies a multi-billion dollar semiconductor fabrication supply chain.',
      visualIntent: 'Layered archival investigation of 3nm wafer engineering and cleanroom lithography',
      visualType: 'editorial-paper',
      primarySubject: '3nm Silicon Wafer & Extreme Lithography',
      visualMetaphor: 'Microscopic engineering confronting physical energy barriers',
      camera: { type: 'pan-left', intensity: 0.18 },
      composition: { layout: 'editorial-split', subjectPosition: 'center', scale: 1.0 },
      typography: {
        headline: 'THE HARDWARE CEILING',
        supportingText: 'Multi-billion dollar cleanroom lithography',
        hierarchy: 'HEADLINE',
        position: 'top-left',
      },
      visualLanguage: 'editorial-paper',
      visualBeats: [
        {
          id: 's2-b1',
          beatIndex: 0,
          startFrame: 0,
          durationInFrames: 90,
          narrativePurpose: 'Archival documentation of fabrication limits',
          visualIntent: 'Layered archival document cards with verified patent stamps',
          primaryVisual: 'editorial-paper',
          secondaryVisuals: [],
          assets: [{
            type: 'archive',
            subject: '3nm Silicon Wafer Schematics',
            url: ASSET_REGISTRY[1].url,
            treatment: 'archival_grain',
            aspectRatio: '16:9',
          }],
          layers: ['background', 'midground', 'subject', 'typography'],
          camera: { movement: 'pan-left', intensity: 0.18, easing: 'ease-out', focalPoint: { x: 50, y: 50 } },
          motion: ['spring_in'],
          typography: {
            treatment: 'editorial_kinetic',
            headline: '3NM WAFER FABRICATION',
            emphasisWords: ['3NM', 'WAFER'],
            position: 'top',
          },
          transition: { type: 'fade', durationFrames: 10, sharedGeometry: 'none', direction: 'right' },
          props: {
            sourceTag: 'PATENT // TSMC-3NM-891',
            cards: [
              { title: 'In-Memory 3nm Logic Cell', value: '0.12 pJ / bit', annotation: 'Direct SRAM-Logic Interconnect', tag: 'EFFICIENCY', rotation: -2.2 },
              { title: 'Co-Packaged Optics Array', value: '25.6 Tb / s', annotation: 'Optical Interconnect Bandwidth', tag: 'THROUGHPUT', rotation: 2.8 },
            ],
          },
        },
        {
          id: 's2-b2',
          beatIndex: 1,
          startFrame: 90,
          durationInFrames: 90,
          narrativePurpose: 'Reveal cleanroom complexity',
          visualIntent: 'Archival technical cards with verified stamps',
          primaryVisual: 'editorial-paper',
          secondaryVisuals: [],
          assets: [],
          layers: ['background', 'midground', 'subject', 'foreground', 'typography'],
          camera: { movement: 'push', intensity: 0.22, easing: 'ease-out', focalPoint: { x: 50, y: 50 } },
          motion: ['counter_start'],
          typography: {
            treatment: 'keyword_spotlight',
            headline: 'SUB-NANOMETER TOLERANCE',
            emphasisWords: ['SUB-NANOMETER'],
            position: 'top',
          },
          transition: { type: 'fade', durationFrames: 10, sharedGeometry: 'none', direction: 'right' },
          props: {
            sourceTag: 'ASML HIGH-NA EUV // 2026',
            cards: [
              { title: 'High-NA EUV Optics', value: '0.55 NA', annotation: 'Extreme Ultraviolet Precision', tag: 'LITHOGRAPHY', rotation: -1.8 },
              { title: 'Wafer Yield Efficiency', value: '94.8 %', annotation: 'Commercial Production Scale', tag: 'FAB YIELD', rotation: 2.2 },
            ],
          },
        },
      ],
      props: {
        chapter: '01',
        chapterTitle: 'PHYSICAL CONSTRAINTS',
        quote: 'Behind every frontier model is a multi-billion dollar cleanroom lithography pipeline operating at sub-atomic precision.',
        source: 'Global Semiconductor Review // IEEE 2026',
        sourceTag: 'PATENT // TSMC-3NM-891',
        cards: [
          { title: 'In-Memory 3nm Logic Cell', value: '0.12 pJ / bit', annotation: 'Direct SRAM-Logic Interconnect', tag: 'EFFICIENCY', rotation: -2.2 },
          { title: 'Co-Packaged Optics Array', value: '25.6 Tb / s', annotation: 'Optical Interconnect Bandwidth', tag: 'THROUGHPUT', rotation: 2.8 },
        ],
      },
    },

    // Scene 3 (11–18s = 210 frames): DATA STORY
    {
      id: 'scene-3',
      sceneNumber: 3,
      type: 'chart',
      templateId: 'chart-bar',
      title: 'Exponential Compute Density Surge',
      startFrame: 330,
      durationFrames: 210,
      narrationText: 'In just twenty-four months, compute density per megawatt surged by more than four hundred percent.',
      visualIntent: 'Animated benchmark quantifying orders of magnitude performance leap',
      visualType: 'data-story',
      primarySubject: 'Compute Efficiency & Power Scaling Curve',
      visualMetaphor: 'Exponential divergence separating legacy hardware from next-gen architectures',
      camera: { type: 'push', intensity: 0.2 },
      composition: { layout: 'data-grid', subjectPosition: 'center', scale: 1.0 },
      typography: {
        headline: 'COMPUTE EFFICIENCY BENCHMARK',
        supportingText: 'PFLOPS / MegaWatt Scaling Across Generations',
        hierarchy: 'DATA',
        position: 'top',
      },
      visualLanguage: 'data-story',
      visualBeats: [
        {
          id: 's3-b1',
          beatIndex: 0,
          startFrame: 0,
          durationInFrames: 105,
          narrativePurpose: 'Establish benchmark scale across hardware generations',
          visualIntent: 'Animated comparative gradient bars with real-time numeric counter',
          primaryVisual: 'data-story',
          secondaryVisuals: [],
          assets: [],
          layers: ['background', 'subject', 'typography'],
          camera: { movement: 'push', intensity: 0.2, easing: 'ease-out', focalPoint: { x: 50, y: 50 } },
          motion: ['spring_in'],
          typography: {
            treatment: 'editorial_kinetic',
            headline: 'COMPUTE DENSITY PER MEGAWATT',
            emphasisWords: ['COMPUTE', 'DENSITY'],
            position: 'top',
          },
          transition: { type: 'fade', durationFrames: 10, sharedGeometry: 'none', direction: 'right' },
          props: {
            chartTitle: 'PFLOPS / MEGAWATT (2020–2026)',
            unit: ' PFLOPS',
            data: [
              { label: 'Legacy GPU Cluster (2020)', value: 12, color: '#f0522a', sublabel: '12 PFLOPS / MW baseline' },
              { label: 'Hopper H100 Array (2023)', value: 68, color: '#ffd166', sublabel: '5.6x compute multiplier' },
              { label: 'Blackwell NVL72 (2026)', value: 290, color: '#00c9a7', sublabel: '24x ultra-scale liquid density' },
            ],
          },
        },
        {
          id: 's3-b2',
          beatIndex: 1,
          startFrame: 105,
          durationInFrames: 105,
          narrativePurpose: 'Highlight 400% efficiency breakthrough',
          visualIntent: 'Glowing accentuation on frontier hardware metric',
          primaryVisual: 'data-story',
          secondaryVisuals: [],
          assets: [],
          layers: ['background', 'subject', 'foreground', 'typography'],
          camera: { movement: 'push', intensity: 0.25, easing: 'ease-out', focalPoint: { x: 50, y: 50 } },
          motion: ['counter_start'],
          typography: {
            treatment: 'keyword_spotlight',
            headline: '400% EFFICIENCY SURGE',
            emphasisWords: ['400%'],
            position: 'top',
          },
          transition: { type: 'fade', durationFrames: 10, sharedGeometry: 'none', direction: 'right' },
          props: {
            chartTitle: 'ENERGY EFFICIENCY MULTIPLIER',
            unit: ' PFLOPS',
            data: [
              { label: 'Legacy GPU Cluster (2020)', value: 12, color: '#f0522a', sublabel: '12 PFLOPS / MW baseline' },
              { label: 'Hopper H100 Array (2023)', value: 68, color: '#ffd166', sublabel: '5.6x compute multiplier' },
              { label: 'Blackwell NVL72 (2026)', value: 290, color: '#00c9a7', sublabel: '24x ultra-scale liquid density' },
            ],
          },
        },
      ],
      props: {
        headline: 'COMPUTE EFFICIENCY BENCHMARK',
        chartTitle: 'PFLOPS / MEGAWATT (2020–2026)',
        unit: ' PFLOPS',
        data: [
          { label: 'Legacy GPU Cluster (2020)', value: 12, color: '#f0522a', sublabel: '12 PFLOPS / MW baseline' },
          { label: 'Hopper H100 Array (2023)', value: 68, color: '#ffd166', sublabel: '5.6x compute multiplier' },
          { label: 'Blackwell NVL72 (2026)', value: 290, color: '#00c9a7', sublabel: '24x ultra-scale liquid density' },
        ],
      },
    },

    // Scene 4 (18–25s = 210 frames): GEOGRAPHIC MAP
    {
      id: 'scene-4',
      sceneNumber: 4,
      type: 'map',
      templateId: 'map-geo',
      title: 'Transcontinental Sovereign Grid',
      startFrame: 540,
      durationFrames: 210,
      narrationText: 'Across Taiwan, Silicon Valley, and Europe, sovereign clusters are linking high-bandwidth optical grids.',
      visualIntent: 'Full-canvas geographic visualization of global sovereign clusters and dark fiber arcs',
      visualType: 'geographic-story',
      primarySubject: 'Transcontinental Dark Fiber & Fab Alliance',
      visualMetaphor: 'Geopolitical matrix connecting capital, silicon, and clean energy',
      camera: { type: 'zoom-region', intensity: 0.22, focalPoint: { x: 50, y: 45 } },
      composition: { layout: 'full-canvas-map', subjectPosition: 'center', scale: 1.0 },
      typography: {
        headline: 'GLOBAL SILICON ALLIANCE',
        supportingText: 'High-Bandwidth Transcontinental Transit Arcs',
        hierarchy: 'HEADLINE',
        position: 'top-left',
      },
      visualLanguage: 'geographic-story',
      visualBeats: [
        {
          id: 's4-b1',
          beatIndex: 0,
          startFrame: 0,
          durationInFrames: 105,
          narrativePurpose: 'Establish global geographic grid',
          visualIntent: 'World map with glowing nodes and dark fiber route arcs',
          primaryVisual: 'geographic-story',
          secondaryVisuals: [],
          assets: [{
            type: 'map',
            subject: 'Global Satellite Dark Fiber Grid',
            url: ASSET_REGISTRY[3].url,
            treatment: 'standard',
            aspectRatio: '16:9',
          }],
          layers: ['background', 'subject', 'typography'],
          camera: { movement: 'zoom-region', intensity: 0.2, easing: 'ease-out', focalPoint: { x: 50, y: 45 } },
          motion: ['spring_in'],
          typography: {
            treatment: 'editorial_kinetic',
            headline: 'TRANSCONTINENTAL FIBER ARCS',
            emphasisWords: ['TRANSCONTINENTAL', 'FIBER'],
            position: 'top',
          },
          transition: { type: 'fade', durationFrames: 10, sharedGeometry: 'none', direction: 'right' },
          props: {
            regionName: 'GLOBAL SOVEREIGN GRID',
            markers: [
              { id: 'taiwan', label: 'Taiwan (TSMC)', x: 78, y: 52, info: '3nm Wafer Fab Hub', active: true },
              { id: 'sv', label: 'Silicon Valley', x: 24, y: 38, info: 'Neural Architecture Cluster', active: true },
              { id: 'europe', label: 'Munich (ASML / Zeiss)', x: 48, y: 30, info: 'EUV Optics Center', active: true },
            ],
            routes: [
              { from: 'europe', to: 'taiwan', label: 'High-NA Lithography Optics' },
              { from: 'taiwan', to: 'sv', label: 'Sub-3nm Silicon Shipments' },
            ],
          },
        },
        {
          id: 's4-b2',
          beatIndex: 1,
          startFrame: 105,
          durationInFrames: 105,
          narrativePurpose: 'Zoom into Taiwan-Silicon Valley interconnect',
          visualIntent: 'Pulsing radar node focus',
          primaryVisual: 'geographic-story',
          secondaryVisuals: [],
          assets: [],
          layers: ['background', 'subject', 'foreground', 'typography'],
          camera: { movement: 'push', intensity: 0.25, easing: 'ease-out', focalPoint: { x: 78, y: 52 } },
          motion: ['diagram_pulse'],
          typography: {
            treatment: 'keyword_spotlight',
            headline: 'OPTICAL TRANSIT ACTIVE',
            emphasisWords: ['OPTICAL'],
            position: 'top',
          },
          transition: { type: 'fade', durationFrames: 10, sharedGeometry: 'none', direction: 'right' },
          props: {
            regionName: 'ASIA-PACIFIC & AMERICAS',
            markers: [
              { id: 'taiwan', label: 'Taiwan (TSMC)', x: 78, y: 52, info: '3nm Wafer Fab Hub', active: true },
              { id: 'sv', label: 'Silicon Valley', x: 24, y: 38, info: 'Neural Architecture Cluster', active: true },
              { id: 'europe', label: 'Munich (ASML / Zeiss)', x: 48, y: 30, info: 'EUV Optics Center', active: true },
            ],
            routes: [
              { from: 'europe', to: 'taiwan', label: 'High-NA Lithography Optics' },
              { from: 'taiwan', to: 'sv', label: 'Sub-3nm Silicon Shipments' },
            ],
          },
        },
      ],
      props: {
        headline: 'GLOBAL SILICON ALLIANCE',
        regionName: 'GLOBAL ALLIANCE',
        markers: [
          { id: 'taiwan', label: 'Taiwan (TSMC)', x: 78, y: 52, info: '3nm Wafer Fab Hub', active: true },
          { id: 'sv', label: 'Silicon Valley', x: 24, y: 38, info: 'Neural Architecture Cluster', active: true },
          { id: 'europe', label: 'Munich (ASML / Zeiss)', x: 48, y: 30, info: 'EUV Optics Center', active: true },
        ],
        routes: [
          { from: 'europe', to: 'taiwan', label: 'High-NA Lithography Optics' },
          { from: 'taiwan', to: 'sv', label: 'Sub-3nm Silicon Shipments' },
        ],
      },
    },

    // Scene 5 (25–33s = 240 frames): HUMAN/TECH CUTOUT COLLAGE
    {
      id: 'scene-5',
      sceneNumber: 5,
      type: 'cutout',
      templateId: 'cutout-explainer',
      title: 'Human-Silicon Co-Design',
      startFrame: 750,
      durationFrames: 240,
      narrationText: 'By compiling algorithms directly into physical silicon logic, software latency is completely eliminated.',
      visualIntent: 'Multi-layer cutout composition fusing human engineering with silicon telemetry',
      visualType: 'cutout-explainer',
      primarySubject: 'Chief Systems Architect Cutout + Wafer Telemetry',
      visualMetaphor: 'Human engineering mastery orchestrating billion-transistor complexity',
      camera: { type: 'orbit', intensity: 0.24 },
      composition: { layout: 'cutout-layered', subjectPosition: 'left', scale: 1.1 },
      typography: {
        headline: 'DIRECT SILICON CO-DESIGN',
        supportingText: 'Zero-overhead algorithm compilation into gate logic',
        hierarchy: 'HEADLINE',
        position: 'right',
      },
      visualLanguage: 'cutout-explainer',
      visualBeats: [
        {
          id: 's5-b1',
          beatIndex: 0,
          startFrame: 0,
          durationInFrames: 120,
          narrativePurpose: 'Present lead system architect cutout and wafer telemetry',
          visualIntent: 'Large-scale cutout subject with glowing outline and background traces',
          primaryVisual: 'cutout-explainer',
          secondaryVisuals: [],
          assets: [{
            type: 'photo',
            subject: 'Lead Silicon Systems Architect',
            url: ASSET_REGISTRY[4].url,
            treatment: 'cutout_shadow',
            aspectRatio: '16:9',
          }],
          layers: ['background', 'midground', 'subject', 'typography'],
          camera: { movement: 'orbit', intensity: 0.22, easing: 'ease-out', focalPoint: { x: 40, y: 50 } },
          motion: ['spring_in'],
          typography: {
            treatment: 'editorial_kinetic',
            headline: 'DIRECT SILICON COMPILATION',
            emphasisWords: ['DIRECT', 'SILICON'],
            position: 'right',
          },
          transition: { type: 'fade', durationFrames: 10, sharedGeometry: 'none', direction: 'right' },
          props: {
            imageUrl: ASSET_REGISTRY[4].url,
            headline: 'DIRECT SILICON COMPILATION',
            subtext: 'Translating models directly into physical gate circuits',
            callouts: [
              { title: 'Zero Interrupt Latency', desc: 'Direct gate-level execution without OS overhead' },
              { title: 'In-Situ SRAM Array', desc: 'Sub-nanosecond memory eliminates bus bottleneck' },
            ],
          },
        },
        {
          id: 's5-b2',
          beatIndex: 1,
          startFrame: 120,
          durationInFrames: 120,
          narrativePurpose: 'Reveal telemetry callouts',
          visualIntent: 'Layered callout cards with verified data stamps',
          primaryVisual: 'cutout-explainer',
          secondaryVisuals: [],
          assets: [],
          layers: ['background', 'midground', 'subject', 'foreground', 'typography'],
          camera: { movement: 'push', intensity: 0.26, easing: 'ease-out', focalPoint: { x: 50, y: 50 } },
          motion: ['counter_start'],
          typography: {
            treatment: 'keyword_spotlight',
            headline: 'ZERO LATENCY ARCHITECTURE',
            emphasisWords: ['ZERO', 'LATENCY'],
            position: 'right',
          },
          transition: { type: 'fade', durationFrames: 10, sharedGeometry: 'none', direction: 'right' },
          props: {
            imageUrl: ASSET_REGISTRY[4].url,
            headline: 'ZERO LATENCY ARCHITECTURE',
            subtext: 'Translating models directly into physical gate circuits',
            callouts: [
              { title: 'Deterministic Timeline', desc: 'Hardware-level synchronization' },
              { title: 'Sub-40°C Liquid Thermal', desc: 'Direct-to-die dissipation matrix' },
            ],
          },
        },
      ],
      props: {
        imageUrl: ASSET_REGISTRY[4].url,
        headline: 'DIRECT SILICON COMPILATION',
        subtext: 'Translating models directly into physical gate circuits',
        callouts: [
          { title: 'Zero Interrupt Latency', desc: 'Direct gate-level execution without OS overhead' },
          { title: 'In-Situ SRAM Array', desc: 'Sub-nanosecond memory eliminates bus bottleneck' },
          { title: 'Sub-40°C Liquid Thermal', desc: 'Direct-to-die dissipation matrix' },
        ],
      },
    },

    // Scene 6 (33–40s = 210 frames): INFRASTRUCTURE / CONSEQUENCE
    {
      id: 'scene-6',
      sceneNumber: 6,
      type: 'statistic',
      templateId: 'statistic-big',
      title: 'Throughput Expansion Payoff',
      startFrame: 990,
      durationFrames: 210,
      narrationText: 'The result is a hundred-fold expansion in total throughput, transforming global digital intelligence.',
      visualIntent: 'High-density technical schematic and big-number payoff',
      visualType: 'technical-diagram',
      primarySubject: 'Optical Interconnect Floorplan & Scale Multiplier',
      visualMetaphor: 'Unprecedented physical scale operating with zero latency bottleneck',
      camera: { type: 'push', intensity: 0.24 },
      composition: { layout: 'schematic-metric', subjectPosition: 'center', scale: 1.0 },
      typography: {
        headline: 'THROUGHPUT MULTIPLIER',
        supportingText: 'Hundred-fold expansion in continuous compute velocity',
        hierarchy: 'DATA',
        position: 'top',
      },
      visualLanguage: 'technical-diagram',
      visualBeats: [
        {
          id: 's6-b1',
          beatIndex: 0,
          startFrame: 0,
          durationInFrames: 105,
          narrativePurpose: 'Display active co-packaged optical bus logic',
          visualIntent: 'Animated technical schematic with pulsing data packet streams',
          primaryVisual: 'technical-diagram',
          secondaryVisuals: [],
          assets: [],
          layers: ['background', 'subject', 'typography'],
          camera: { movement: 'push', intensity: 0.22, easing: 'ease-out', focalPoint: { x: 50, y: 50 } },
          motion: ['spring_in'],
          typography: {
            treatment: 'editorial_kinetic',
            headline: 'CO-PACKAGED OPTICAL MATRIX',
            emphasisWords: ['CO-PACKAGED', 'OPTICAL'],
            position: 'top',
          },
          transition: { type: 'fade', durationFrames: 10, sharedGeometry: 'none', direction: 'right' },
          props: {
            headline: 'CO-PACKAGED OPTICAL MATRIX',
            nodes: [
              { id: 'optics', label: 'Co-Packaged Optics', sublabel: '25.6 Tbps Bandwidth', x: 25, y: 50, highlighted: true },
              { id: 'logic', label: '3nm Compute Cores', sublabel: 'Direct Gate Layer', x: 75, y: 50, highlighted: true },
              { id: 'sram', label: 'In-Memory SRAM', sublabel: 'Zero Transit Loss', x: 50, y: 25, highlighted: false },
              { id: 'thermal', label: 'Liquid Thermal Matrix', sublabel: 'Sub-40°C Direct Cooling', x: 50, y: 75, highlighted: false },
            ],
            connections: [
              { from: 'optics', to: 'logic', label: 'Ultra-Low Latency Bus' },
              { from: 'sram', to: 'logic', label: 'High-Density Interconnect' },
              { from: 'thermal', to: 'logic', label: 'Thermodynamic Dissipation' },
            ],
          },
        },
        {
          id: 's6-b2',
          beatIndex: 1,
          startFrame: 105,
          durationInFrames: 105,
          narrativePurpose: 'Emphasize hundred-fold breakthrough',
          visualIntent: 'Big-number metric reveal alongside active logic schematic',
          primaryVisual: 'cinematic-statistic',
          secondaryVisuals: ['technical-diagram'],
          assets: [],
          layers: ['background', 'subject', 'foreground', 'typography'],
          camera: { movement: 'parallax', intensity: 0.26, easing: 'ease-out', focalPoint: { x: 50, y: 50 } },
          motion: ['counter_start'],
          typography: {
            treatment: 'keyword_spotlight',
            headline: '100X VELOCITY MULTIPLIER',
            emphasisWords: ['100X'],
            position: 'top',
          },
          transition: { type: 'fade', durationFrames: 10, sharedGeometry: 'none', direction: 'right' },
          props: {
            headline: 'THROUGHPUT MULTIPLIER',
            targetValue: 100,
            suffix: 'X',
            subtext: 'Hundred-fold expansion in total continuous throughput',
          },
        },
      ],
      props: {
        headline: 'THROUGHPUT MULTIPLIER',
        targetValue: 100,
        suffix: 'X',
        tag: 'MEASURED PERFORMANCE MULTIPLIER',
        subtext: 'Hundred-fold expansion in total continuous throughput across optical fabrics.',
      },
    },

    // Scene 7 (40–45s = 150 frames): STRONG CONCLUSION
    {
      id: 'scene-7',
      sceneNumber: 7,
      type: 'outro',
      templateId: 'outro-cta',
      title: 'Channel Outro',
      startFrame: 1200,
      durationFrames: 150,
      narrationText: 'This is not just faster computing. It is the physical foundation of the next era.',
      visualIntent: 'Crisp editorial conclusion with glowing signature branding',
      visualType: 'cinematic-outro',
      primarySubject: 'Catalyst Editorial Monogram & Verification Stamp',
      visualMetaphor: 'Authoritative journalistic closure',
      camera: { type: 'push', intensity: 0.15 },
      composition: { layout: 'hero-outro', subjectPosition: 'center', scale: 1.0 },
      typography: {
        headline: 'CATALYST EDITORIAL',
        supportingText: 'SUBSCRIBE FOR HARDWARE DEEP DIVES',
        hierarchy: 'DISPLAY',
        position: 'center',
      },
      visualLanguage: 'cinematic-outro',
      visualBeats: [
        {
          id: 's7-b1',
          beatIndex: 0,
          startFrame: 0,
          durationInFrames: 150,
          narrativePurpose: 'Deliver authoritative conclusion and brand CTA',
          visualIntent: 'Signature branding with animated accent glow',
          primaryVisual: 'cinematic-outro',
          secondaryVisuals: [],
          assets: [],
          layers: ['background', 'subject', 'typography'],
          camera: { movement: 'push', intensity: 0.15, easing: 'ease-out', focalPoint: { x: 50, y: 50 } },
          motion: ['spring_in'],
          typography: {
            treatment: 'editorial_kinetic',
            headline: 'CATALYST EDITORIAL',
            emphasisWords: ['CATALYST'],
            position: 'center',
          },
          transition: { type: 'fade', durationFrames: 10, sharedGeometry: 'none', direction: 'right' },
          props: {
            channelName: 'CATALYST',
            ctaText: 'SUBSCRIBE FOR HARDWARE INVESTIGATIONS',
            tagline: 'Engineering the Physical Frontier',
            ctaTitle: 'Subscribe for Daily Deep Dives',
            handle: '@CatalystStudio',
          },
        },
      ],
      props: {
        channelName: 'CATALYST',
        ctaTitle: 'Subscribe for Daily Deep Dives',
        handle: '@CatalystStudio',
        ctaText: 'SUBSCRIBE FOR HARDWARE INVESTIGATIONS',
        tagline: 'Engineering the Physical Frontier',
        subtext: 'Next investigation drops tomorrow at 09:00 UTC',
      },
    },
  ],
  audio: {
    voiceoverVolume: 1.0,
    musicVolume: 0.22,
    duckingPercentage: 0.35,
    sfx: [
      { sfxId: 'whoosh-1', url: '', frame: 0, volume: 0.7 },
      { sfxId: 'impact-1', url: '', frame: 6, volume: 0.9 },
      { sfxId: 'data-ping', url: '', frame: 335, volume: 0.6 },
      { sfxId: 'riser', url: '', frame: 990, volume: 0.8 },
    ],
  },
  assets: ASSET_REGISTRY.map((a) => ({
    id: a.id,
    type: a.type,
    url: a.url,
    description: a.description,
  })),
  metadata: {
    topic: 'The Race to Build the World’s Most Powerful AI Infrastructure',
    targetPlatform: 'youtube-shorts',
    targetAudience: 'Hardware Engineers, Researchers & Tech Leaders',
    generatedAt: new Date().toISOString(),
    versionTag: 'v2.0.0',
  },
};
