import type { VideoSpec } from './types';

export const SAMPLE_SHOWCASE_SPEC_2: VideoSpec = {
  version: '1.0.0',
  id: 'showcase-robotics-inflection-2026',
  title: 'The Robotics Inflection: Why Humanoid Hardware Succeeded',
  description: 'A 45-second documentary investigating the breakthrough in actuator torque density and spatial vision models.',
  composition: {
    format: '9:16',
    width: 1080,
    height: 1920,
    fps: 30,
    durationInFrames: 1350,
  },
  brand: {
    brandId: 'tech-futurist',
    name: 'Tech Futurist',
    colors: {
      primary: '#6366f1',
      secondary: '#06b6d4',
      accent: '#00c9a7',
      background: '#030712',
      surface: '#0f172a',
      text: '#f8fafc',
      textMuted: '#64748b',
    },
    typography: {
      fontFamilyHeading: 'Inter, system-ui, sans-serif',
      fontFamilyBody: 'Inter, system-ui, sans-serif',
      fontFamilyMono: 'JetBrains Mono, monospace',
      headingWeight: '900',
      bodyWeight: '500',
    },
    motionStyle: 'kinetic',
    textures: {
      paperTexture: true,
      grainIntensity: 0.06,
      halftoneEffect: false,
      vignette: true,
    },
    captionStyle: {
      preset: 'vox-editorial',
      fontSize: 44,
      highlightColor: '#00c9a7',
      activeTextColor: '#000000',
      inactiveTextColor: '#ffffff',
      boxBackground: 'rgba(3, 7, 18, 0.85)',
    },
  },
  narration: {
    durationSeconds: 45,
    transcript: 'For fifty years, humanoid robotics was held back by heavy motors and fragile gears. But in early 2026, solid-state harmonic actuators changed the physics forever. In factories across Tokyo, Shenzhen, and Austin, over ten thousand humanoid units are now operating continuously. By pairing spatial foundation models with low-cost precision actuators, unit costs plummeted by eighty-four percent. The boundary between digital intelligence and physical labor has officially dissolved.',
    words: [
      { word: 'For', start: 0.2, end: 0.5 },
      { word: 'fifty', start: 0.5, end: 0.9 },
      { word: 'years,', start: 1.0, end: 1.5 },
      { word: 'robotics', start: 1.6, end: 2.2 },
      { word: 'was', start: 2.3, end: 2.5 },
      { word: 'held', start: 2.6, end: 2.9 },
      { word: 'back.', start: 3.0, end: 3.8 },
      // Scene 2
      { word: 'Heavy', start: 4.1, end: 4.6 },
      { word: 'motors', start: 4.7, end: 5.2 },
      { word: 'and', start: 5.3, end: 5.5 },
      { word: 'fragile', start: 5.6, end: 6.2 },
      { word: 'gears', start: 6.3, end: 6.8 },
      { word: 'limited', start: 6.9, end: 7.5 },
      { word: 'physical', start: 7.6, end: 8.2 },
      { word: 'agility.', start: 8.3, end: 9.0 },
      // Scene 3
      { word: 'Then,', start: 9.2, end: 9.6 },
      { word: 'solid-state', start: 9.7, end: 10.5 },
      { word: 'actuators', start: 10.6, end: 11.4 },
      { word: 'slashed', start: 11.5, end: 12.0 },
      { word: 'manufacturing', start: 12.1, end: 13.0 },
      { word: 'costs', start: 13.1, end: 13.6 },
      { word: 'by', start: 13.7, end: 13.9 },
      { word: 'eighty-four', start: 14.0, end: 14.8 },
      { word: 'percent.', start: 14.9, end: 15.8 },
      // Scene 4
      { word: 'Across', start: 16.1, end: 16.6 },
      { word: 'Tokyo,', start: 16.7, end: 17.4 },
      { word: 'Shenzhen,', start: 17.5, end: 18.3 },
      { word: 'and', start: 18.4, end: 18.6 },
      { word: 'Austin,', start: 18.7, end: 19.5 },
      { word: 'production', start: 19.8, end: 20.6 },
      { word: 'lines', start: 20.7, end: 21.3 },
      { word: 'scaled.', start: 21.4, end: 22.4 },
      // Scene 5
      { word: 'By', start: 23.0, end: 23.2 },
      { word: 'pairing', start: 23.3, end: 23.9 },
      { word: 'spatial', start: 24.0, end: 24.6 },
      { word: 'intelligence', start: 24.7, end: 25.6 },
      { word: 'with', start: 25.7, end: 25.9 },
      { word: 'harmonic', start: 26.0, end: 26.7 },
      { word: 'drives,', start: 26.8, end: 27.5 },
      { word: 'dexterity', start: 28.0, end: 28.8 },
      { word: 'reached', start: 28.9, end: 29.5 },
      { word: 'parity.', start: 29.6, end: 31.0 },
      // Scene 6
      { word: 'Over', start: 32.0, end: 32.4 },
      { word: 'ten', start: 32.5, end: 32.8 },
      { word: 'thousand', start: 32.9, end: 33.6 },
      { word: 'units', start: 33.7, end: 34.2 },
      { word: 'are', start: 34.3, end: 34.5 },
      { word: 'active', start: 34.6, end: 35.2 },
      { word: 'worldwide.', start: 35.3, end: 36.5 },
      { word: 'The', start: 37.0, end: 37.2 },
      { word: 'physical', start: 37.3, end: 37.9 },
      { word: 'frontier', start: 38.0, end: 38.7 },
      { word: 'is', start: 38.8, end: 39.0 },
      { word: 'here.', start: 39.1, end: 39.8 },
      // Scene 7
      { word: 'Follow', start: 40.2, end: 40.7 },
      { word: 'Catalyst', start: 40.8, end: 41.4 },
      { word: 'for', start: 41.5, end: 41.7 },
      { word: 'daily', start: 41.8, end: 42.3 },
      { word: 'deep', start: 42.4, end: 42.8 },
      { word: 'dives.', start: 42.9, end: 44.2 },
    ],
  },
  scenes: [
    {
      id: 's2-1',
      sceneNumber: 1,
      type: 'hook',
      templateId: 'hook-primary',
      title: 'The Robotics Inflection',
      startFrame: 0,
      durationFrames: 120,
      camera: { type: 'push', intensity: 0.2 },
      props: {
        tag: 'SPECIAL REPORT // HARDWARE 2026',
        headline: 'THE ROBOTICS INFLECTION',
        subtext: 'How solid-state actuators broke the physical barrier.',
        highlightWords: ['ROBOTICS', 'INFLECTION', 'BARRIER'],
      },
    },
    {
      id: 's2-2',
      sceneNumber: 2,
      type: 'editorial',
      templateId: 'editorial-quote',
      title: 'The Actuator Breakthrough',
      startFrame: 120,
      durationFrames: 150,
      camera: { type: 'pan-left', intensity: 0.12 },
      props: {
        chapter: '01',
        chapterTitle: 'PHYSICAL CONSTRAINTS',
        quote: 'For decades software lived in isolation. The integration of high-density electromagnetic drives brought models into physical space.',
        source: 'Robotics Engineering Review (2026)',
        keyPoints: [
          'High torque-to-weight harmonic motors',
          'Millisecond spatial-visual feedback loops',
          'Autonomous zero-shot task transfer',
        ],
      },
    },
    {
      id: 's2-3',
      sceneNumber: 3,
      type: 'chart',
      templateId: 'chart-bar',
      title: 'Actuator Cost Reduction',
      startFrame: 270,
      durationFrames: 210,
      camera: { type: 'push', intensity: 0.15 },
      props: {
        headline: 'Unit Cost vs Torque Density',
        chartTitle: 'COST DEFLECTION RATE',
        unit: '%',
        data: [
          { label: 'Hydraulic Actuators (2020)', value: 95, color: '#f0522a' },
          { label: 'Planetary Gearboxes (2023)', value: 60, color: '#ffd166' },
          { label: 'Solid-State Harmonic (2026)', value: 16, color: '#00c9a7' },
        ],
      },
    },
    {
      id: 's2-4',
      sceneNumber: 4,
      type: 'map',
      templateId: 'map-geo',
      title: 'Global Manufacturing Nodes',
      startFrame: 480,
      durationFrames: 210,
      camera: { type: 'zoom-region', intensity: 0.2, focalPoint: { x: 75, y: 48 } },
      props: {
        headline: 'Global Production Nodes',
        regionName: 'ASIA-PACIFIC & AMERICAS',
        markers: [
          { id: '1', label: 'Tokyo', x: 78, y: 48, accentColor: '#00c9a7', info: 'Harmonic Drive R&D' },
          { id: '2', label: 'Shenzhen', x: 72, y: 55, accentColor: '#ffd166', info: 'Precision Mass Assembly' },
          { id: '3', label: 'Austin', x: 25, y: 46, accentColor: '#6366f1', info: 'Vision-Language-Action Cluster' },
        ],
      },
    },
    {
      id: 's2-5',
      sceneNumber: 5,
      type: 'cutout',
      templateId: 'cutout-explainer',
      title: 'The Spatial Intelligence Stack',
      startFrame: 690,
      durationFrames: 270,
      camera: { type: 'parallax', intensity: 0.15 },
      props: {
        headline: 'Spatial Intelligence Stack',
        callouts: [
          { title: 'Harmonic Motors', desc: 'Sub-millimeter positional accuracy' },
          { title: 'Vision-Language-Action', desc: 'Real-time multi-modal spatial reasoning' },
          { title: 'Edge Neural Coprocessors', desc: 'Zero-latency local motor reflex execution' },
        ],
      },
    },
    {
      id: 's2-6',
      sceneNumber: 6,
      type: 'statistic',
      templateId: 'statistic-big',
      title: 'Deployment Scale',
      startFrame: 960,
      durationFrames: 240,
      camera: { type: 'push', intensity: 0.2 },
      props: {
        targetValue: 10000,
        prefix: '>',
        suffix: '',
        tag: 'GLOBAL INDUSTRIAL FOOTPRINT',
        headline: 'Units in Production',
        subtext: 'Operating continuously across cleanrooms, warehouses, and logistics hubs.',
      },
    },
    {
      id: 's2-7',
      sceneNumber: 7,
      type: 'outro',
      templateId: 'outro-cta',
      title: 'Channel Outro',
      startFrame: 1200,
      durationFrames: 150,
      camera: { type: 'push', intensity: 0.1 },
      props: {
        ctaTitle: 'Follow for Hardware Deep Dives',
        handle: '@CatalystStudio',
        subtext: 'Next episode drops tomorrow at 09:00 UTC',
      },
    },
  ],
  audio: {
    voiceoverVolume: 1.0,
    musicVolume: 0.2,
    duckingPercentage: 0.35,
    sfx: [],
  },
  assets: [],
  metadata: {
    topic: 'Humanoid Robotics Breakthrough 2026',
    targetPlatform: 'youtube-shorts',
    targetAudience: 'Engineers & Tech Leaders',
    generatedAt: new Date().toISOString(),
    versionTag: 'v1.0.0',
  },
};
