import type { VideoSpec } from './types';

export const SAMPLE_SHOWCASE_SPEC: VideoSpec = {
  version: '1.0.0',
  id: 'showcase-ai-breakthrough-2026',
  title: 'The AI Video Revolution: Beyond Frame Generation',
  description: 'A 45-second documentary explainer investigating how deterministic AI engines replace legacy video production.',
  composition: {
    format: '9:16',
    width: 1080,
    height: 1920,
    fps: 30,
    durationInFrames: 1350, // 45s @ 30fps
  },
  brand: {
    brandId: 'catalyst-editorial',
    name: 'Catalyst Editorial',
    colors: {
      primary: '#f0522a',
      secondary: '#00c9a7',
      accent: '#ffd166',
      background: '#0b0d13',
      surface: '#161922',
      text: '#f8fafc',
      textMuted: '#94a3b8',
    },
    typography: {
      fontFamilyHeading: 'Inter, system-ui, sans-serif',
      fontFamilyBody: 'Inter, system-ui, sans-serif',
      fontFamilyMono: 'JetBrains Mono, monospace',
      headingWeight: '900',
      bodyWeight: '500',
    },
    motionStyle: 'editorial',
    textures: {
      paperTexture: true,
      grainIntensity: 0.08,
      halftoneEffect: false,
      vignette: true,
    },
    captionStyle: {
      preset: 'vox-editorial',
      fontSize: 44,
      highlightColor: '#ffd166',
      activeTextColor: '#000000',
      inactiveTextColor: '#ffffff',
      boxBackground: 'rgba(11, 13, 19, 0.85)',
    },
  },
  narration: {
    durationSeconds: 45,
    transcript: 'For decades, video production demanded massive rendering farms and days of manual keyframing. But a quiet revolution just eliminated that bottleneck. Today, autonomous reasoning engines generate broadcast-grade compositions in real time. Across San Francisco, Tokyo, and Frankfurt, global teams are producing thousands of personalized explainers. The resulting efficiency is staggering: a one hundred times acceleration in creative velocity. This is not the future of video. It is happening right now.',
    words: [
      { word: 'For', start: 0.2, end: 0.5 },
      { word: 'decades,', start: 0.5, end: 1.1 },
      { word: 'video', start: 1.2, end: 1.6 },
      { word: 'production', start: 1.6, end: 2.2 },
      { word: 'demanded', start: 2.3, end: 2.8 },
      { word: 'massive', start: 2.9, end: 3.4 },
      { word: 'rendering', start: 3.5, end: 4.0 },
      // Scene 2
      { word: 'farms', start: 4.1, end: 4.6 },
      { word: 'and', start: 4.7, end: 4.9 },
      { word: 'days', start: 5.0, end: 5.4 },
      { word: 'of', start: 5.5, end: 5.7 },
      { word: 'manual', start: 5.8, end: 6.3 },
      { word: 'keyframing.', start: 6.4, end: 7.2 },
      { word: 'A', start: 7.5, end: 7.7 },
      { word: 'quiet', start: 7.8, end: 8.2 },
      { word: 'revolution', start: 8.3, end: 8.9 },
      // Scene 3
      { word: 'just', start: 9.1, end: 9.4 },
      { word: 'eliminated', start: 9.5, end: 10.2 },
      { word: 'that', start: 10.3, end: 10.6 },
      { word: 'bottleneck.', start: 10.7, end: 11.5 },
      { word: 'Today,', start: 11.8, end: 12.3 },
      { word: 'autonomous', start: 12.4, end: 13.1 },
      { word: 'reasoning', start: 13.2, end: 13.8 },
      { word: 'engines', start: 13.9, end: 14.5 },
      { word: 'generate', start: 14.6, end: 15.2 },
      { word: 'broadcast', start: 15.3, end: 15.9 },
      // Scene 4
      { word: 'compositions.', start: 16.1, end: 17.0 },
      { word: 'Across', start: 17.2, end: 17.7 },
      { word: 'San', start: 17.8, end: 18.1 },
      { word: 'Francisco,', start: 18.2, end: 18.9 },
      { word: 'Tokyo,', start: 19.1, end: 19.8 },
      { word: 'and', start: 20.0, end: 20.2 },
      { word: 'Frankfurt,', start: 20.3, end: 21.2 },
      { word: 'global', start: 21.5, end: 22.1 },
      { word: 'teams', start: 22.2, end: 22.8 },
      // Scene 5
      { word: 'produce', start: 23.1, end: 23.6 },
      { word: 'thousands', start: 23.7, end: 24.4 },
      { word: 'of', start: 24.5, end: 24.7 },
      { word: 'personalized', start: 24.8, end: 25.7 },
      { word: 'editorial', start: 25.8, end: 26.5 },
      { word: 'explainers.', start: 26.6, end: 27.6 },
      { word: 'The', start: 28.0, end: 28.2 },
      { word: 'architecture', start: 28.3, end: 29.3 },
      { word: 'is', start: 29.4, end: 29.6 },
      { word: 'pure', start: 29.7, end: 30.2 },
      { word: 'code.', start: 30.3, end: 31.5 },
      // Scene 6
      { word: 'The', start: 32.0, end: 32.2 },
      { word: 'efficiency', start: 32.3, end: 33.1 },
      { word: 'is', start: 33.2, end: 33.5 },
      { word: 'staggering:', start: 33.6, end: 34.7 },
      { word: 'a', start: 35.0, end: 35.2 },
      { word: 'one', start: 35.3, end: 35.6 },
      { word: 'hundred', start: 35.7, end: 36.3 },
      { word: 'times', start: 36.4, end: 36.9 },
      { word: 'acceleration', start: 37.0, end: 38.2 },
      { word: 'in', start: 38.3, end: 38.5 },
      { word: 'velocity.', start: 38.6, end: 39.5 },
      // Scene 7
      { word: 'This', start: 40.2, end: 40.6 },
      { word: 'is', start: 40.7, end: 40.9 },
      { word: 'not', start: 41.0, end: 41.3 },
      { word: 'the', start: 41.4, end: 41.6 },
      { word: 'future.', start: 41.7, end: 42.4 },
      { word: 'It', start: 42.6, end: 42.8 },
      { word: 'is', start: 42.9, end: 43.1 },
      { word: 'happening', start: 43.2, end: 43.8 },
      { word: 'now.', start: 43.9, end: 44.6 },
    ],
  },
  scenes: [
    // Scene 1: Hook (0–4s = 120 frames)
    {
      id: 'scene-1',
      sceneNumber: 1,
      type: 'hook',
      templateId: 'hook-primary',
      title: 'The AI Video Revolution',
      startFrame: 0,
      durationFrames: 120,
      camera: { type: 'push', intensity: 0.18 },
      props: {
        tag: 'DOCUMENTARY INVESTIGATION',
        headline: 'THE AI VIDEO REVOLUTION',
        subtext: 'Beyond stochastic frame generation.',
        highlightWords: ['AI', 'VIDEO', 'REVOLUTION'],
      },
    },
    // Scene 2: Context / Editorial (4–9s = 150 frames)
    {
      id: 'scene-2',
      sceneNumber: 2,
      type: 'editorial',
      templateId: 'editorial-quote',
      title: 'The Traditional Bottleneck',
      startFrame: 120,
      durationFrames: 150,
      camera: { type: 'pan-left', intensity: 0.12 },
      props: {
        chapter: '01',
        chapterTitle: 'THE EDITORIAL CONTEXT',
        quote: 'Traditional editing was locked to timeline tracks. The new paradigm compiles video like modern software.',
        source: 'Media Architecture Review (2026)',
        keyPoints: [
          'Zero manual rendering queues',
          'Deterministic frame-accurate React code',
          'Sub-second preview latency',
        ],
      },
    },
    // Scene 3: Data Chart (9–16s = 210 frames)
    {
      id: 'scene-3',
      sceneNumber: 3,
      type: 'chart',
      templateId: 'chart-bar',
      title: 'Exponential Velocity Surge',
      startFrame: 270,
      durationFrames: 210,
      camera: { type: 'push', intensity: 0.14 },
      props: {
        headline: 'Adoption & Output Velocity',
        chartTitle: 'PRODUCTION MULTIPLIER',
        unit: '%',
        data: [
          { label: 'Manual Keyframing', value: 18, color: '#94a3b8' },
          { label: 'Generative Diffusion', value: 45, color: '#00c9a7' },
          { label: 'Catalyst Motion OS', value: 96, color: '#ffd166' },
        ],
      },
    },
    // Scene 4: Geo Map (16–23s = 210 frames)
    {
      id: 'scene-4',
      sceneNumber: 4,
      type: 'map',
      templateId: 'map-geo',
      title: 'Global Autonomous Network',
      startFrame: 480,
      durationFrames: 210,
      camera: { type: 'zoom-region', intensity: 0.2, focalPoint: { x: 50, y: 45 } },
      props: {
        headline: 'Global Distributed Infrastructure',
        regionName: 'TRANSIT CORRIDOR',
        markers: [
          { id: '1', label: 'San Francisco', x: 28, y: 44, accentColor: '#00c9a7', info: 'Agent Orchestration' },
          { id: '2', label: 'Tokyo', x: 78, y: 48, accentColor: '#ffd166', info: 'Edge Synthesizer' },
          { id: '3', label: 'Frankfurt', x: 48, y: 35, accentColor: '#f0522a', info: 'Lambda Rendering Cluster' },
        ],
      },
    },
    // Scene 5: Explanation (23–32s = 270 frames)
    {
      id: 'scene-5',
      sceneNumber: 5,
      type: 'cutout',
      templateId: 'cutout-explainer',
      title: 'The Neural Engine',
      startFrame: 690,
      durationFrames: 270,
      camera: { type: 'parallax', intensity: 0.16 },
      props: {
        headline: 'The Neural Engine',
        callouts: [
          { title: 'Claude Intelligence', desc: 'Narrative & visual pacing decisions' },
          { title: 'Remotion Primitives', desc: 'Deterministic React frame rendering' },
          { title: 'S3 & Lambda', desc: 'High-throughput cloud export' },
        ],
      },
    },
    // Scene 6: Payoff / Big Number (32–40s = 240 frames)
    {
      id: 'scene-6',
      sceneNumber: 6,
      type: 'statistic',
      templateId: 'statistic-big',
      title: 'Production Multiplier',
      startFrame: 960,
      durationFrames: 240,
      camera: { type: 'push', intensity: 0.2 },
      props: {
        targetValue: 100,
        prefix: '',
        suffix: 'X',
        tag: 'MEASURED EFFICIENCY GAIN',
        headline: 'Velocity Unleashed',
        subtext: 'From concept to finished 4K broadcast in under sixty seconds.',
      },
    },
    // Scene 7: Outro (40–45s = 150 frames)
    {
      id: 'scene-7',
      sceneNumber: 7,
      type: 'outro',
      templateId: 'outro-cta',
      title: 'Catalyst Studio Call to Action',
      startFrame: 1200,
      durationFrames: 150,
      camera: { type: 'push', intensity: 0.1 },
      props: {
        ctaTitle: 'Follow for Daily Deep Dives',
        handle: '@CatalystStudio',
        subtext: 'Next episode drops tomorrow at 09:00 UTC',
      },
    },
  ],
  audio: {
    voiceoverVolume: 1.0,
    musicVolume: 0.22,
    duckingPercentage: 0.35,
    sfx: [
      { sfxId: 'whoosh-1', url: '', frame: 0, volume: 0.7 },
      { sfxId: 'impact-1', url: '', frame: 6, volume: 0.9 },
      { sfxId: 'data-ping', url: '', frame: 275, volume: 0.6 },
      { sfxId: 'riser', url: '', frame: 960, volume: 0.8 },
    ],
  },
  assets: [],
  metadata: {
    topic: 'AI Video Engines',
    targetPlatform: 'youtube-shorts',
    targetAudience: 'Tech & Creators',
    generatedAt: new Date().toISOString(),
    versionTag: 'v1.0.0',
  },
};
